apiVersion: apps/v1
kind: Deployment
metadata:
  name: webp-converter
  namespace: converter
  labels:
    app: webp-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webp-converter
  template:
    metadata:
      labels:
        app: webp-converter
    spec:
      containers:
      - name: webp-converter
        image: tororomeshi/to-webp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        - name: RUST_LOG
          value: "info"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20